name: YouTube-Short-Daily

on:
  schedule:
    # Scheduled times in UTC to align with peak hours in target regions:
    - cron: '0 13 * * *'  # 15:00 CET/CEST – Europe afternoon
    - cron: '0 15 * * *'  # 17:00 CET/CEST – Europe early evening
    - cron: '0 17 * * *'  # 19:00 CET/CEST – Europe evening
    - cron: '0 19 * * *'  # 21:00 CET/CEST – Europe late evening
    - cron: '0 1 * * *'   # 09:00 CST – China morning
    - cron: '0 11 * * *'  # 19:00 CST – China evening
    - cron: '0 2 * * *'   # 07:30 IST – India morning
    - cron: '0 14 * * *'  # 19:30 IST – India evening
    - cron: '0 20 * * *'  # 15:00 EST – USA afternoon
    - cron: '0 5 * * *'  # 15:00 EST – USA afternoon
    - cron: '0 8 * * *'  # 15:00 EST – USA afternoon
    - cron: '0 22 * * *'  # 15:00 EST – USA afternoon
    - cron: '0 18 * * *'  # 15:00 EST – USA afternoon
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      CLIENT_SECRETS_JSON: ${{ secrets.CLIENT_SECRETS_JSON }}
      TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GAMEPLAY_URL: ${{ secrets.GAMEPLAY_URL }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install lxml[html_clean]>=4.9.0
        pip install -r requirements.txt
        pip install nbconvert>=7.0 ipykernel
        python -m ipykernel install --user --name python3 --display-name "Python 3.11"

    - name: Verify Google Drive access
      run: |
        FILE_ID=$(echo "${{ secrets.GAMEPLAY_URL }}" | grep -oP 'id=\K[^&]+')
        echo "Testing download for file ID: $FILE_ID"
        gdown --version
        gdown --id $FILE_ID -O test.mp4 || \
        curl -L -o test.mp4 "https://drive.google.com/uc?export=download&id=$FILE_ID"
        ls -lh test.mp4
        file test.mp4
        rm test.mp4

    - name: Prepare params file
      run: echo '{}' > params.json

    - name: Execute notebook
      run: |
        jupyter nbconvert --execute --to notebook \
          --inplace "Youtube Automation Trigger - Test 2.ipynb" \
          --ExecutePreprocessor.kernel_name=python3 \
          --ExecutePreprocessor.timeout=1800

    - name: Upload finished MP4
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: short
        path: shorts_final.mp4

    - name: Upload debug info
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: debug-info
        path: |
          *.log
          nbconvert*.out
