name: YouTube-Short-Daily

on:
  schedule:               # 06:00 CET every day
    - cron:  '0 4 * * *'  # GitHub cron uses UTC
  workflow_dispatch:      # adds a manual Run button in the Actions tab

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    env:                             # expose secrets to the notebook
      CLIENT_SECRETS_JSON: ${{ secrets.CLIENT_SECRETS_JSON }}
      TOKEN_JSON:          ${{ secrets.TOKEN_JSON }}
      OPENAI_API_KEY:      ${{ secrets.OPENAI_API_KEY }}
      GAMEPLAY_URL:        ${{ secrets.GAMEPLAY_URL }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - run: pip install -r requirements.txt

      - name: Execute notebook with Papermill
        uses: yaananth/run-notebook@v2
        with:
          notebook: video_flow.ipynb
          params: |
            {"GAMEPLAY_URL": "${{ env.GAMEPLAY_URL }}"}

      - name: Upload finished MP4
        uses: actions/upload-artifact@v4
        with:
          name: short
          path: shorts_final.mp4
