name: YouTube-Short-Daily

on:
  schedule:
    - cron: '0 4 * * *'     # 06:00 CET daily
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    env:
      CLIENT_SECRETS_JSON: ${{ secrets.CLIENT_SECRETS_JSON }}
      TOKEN_JSON:          ${{ secrets.TOKEN_JSON }}
      OPENAI_API_KEY:      ${{ secrets.OPENAI_API_KEY }}
      GAMEPLAY_URL:        ${{ secrets.GAMEPLAY_URL }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install -r requirements.txt

      - name: Execute notebook with Papermill
        uses: yaananth/run-notebook@v2
        with:
          notebook: "Youtube Automation Trigger - Test 1.ipynb"
          params: '{}'                 # ← valid JSON string (empty object)

      - name: Upload finished MP4
        uses: actions/upload-artifact@v4
        with:
          name: short
          path: shorts_final.mp4
