name: YouTube-Short-Daily

on:
  # run every day at 06:00 CET  (= 04:00 UTC)
  schedule:
    - cron: '0 4 * * *'
  # add a green “Run workflow” button in the Actions tab
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    # expose secrets as environment variables
    env:
      CLIENT_SECRETS_JSON: ${{ secrets.CLIENT_SECRETS_JSON }}
      TOKEN_JSON:          ${{ secrets.TOKEN_JSON }}
      OPENAI_API_KEY:      ${{ secrets.OPENAI_API_KEY }}
      GAMEPLAY_URL:        ${{ secrets.GAMEPLAY_URL }}

    steps:
      # 1. pull repo
      - uses: actions/checkout@v4

      # 2. set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. install notebook dependencies
      - run: pip install -r requirements.txt

      # 4. execute the notebook head-less
      - name: Execute notebook with Papermill
        uses: yaananth/run-notebook@v2
        with:
          notebook: video_flow.ipynb
          # 👇 single-line JSON string — must be valid JSON
          params: '{"GAMEPLAY_URL": "${{ env.GAMEPLAY_URL }}"}'

      # 5. keep the rendered short as a GitHub artifact (optional)
      - name: Upload finished MP4
        uses: actions/upload-artifact@v4
        with:
          name: short
          path: shorts_final.mp4
