name: YouTube-Short-Daily-Stories

on:
  # schedule:
  #   - cron: '0 7 * * *'
  #   - cron: '0 8 * * *'
  #   - cron: '0 9 * * *'
  #   - cron: '0 17 * * *'
  #   - cron: '0 23 * * *'
  #   - cron: '0 2 * * *'
  #   - cron: '0 3 * * *'
  #   - cron: '0 4 * * *'
  #   - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      CLIENT_SECRETS_JSON: ${{ secrets.CLIENT_SECRETS_JSON }}
      TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system fonts and Aeneas dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-dejavu ffmpeg espeak libespeak-dev

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install numpy
        pip install -r requirements2.txt
        pip install nbconvert>=7.0 ipykernel

    - name: Prepare Google API credentials
      run: |
        echo "${CLIENT_SECRETS_JSON}" > client_secret.json
        echo "${TOKEN_JSON}" > token.pickle

    - name: Prepare params file
      run: echo '{}' > params.json

    - name: Execute notebook
      run: |
        jupyter nbconvert --execute --to notebook \
          --inplace "YouTube_Automation_v5_0_SHORT_STORIES_TEST.ipynb" \
          --ExecutePreprocessor.kernel_name=python3 \
          --ExecutePreprocessor.timeout=3600

    - name: Upload finished MP4
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: short
        path: shorts_final.mp4
        retention-days: 2

    - name: Upload debug info
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: debug-info
        path: |
          *.log
          nbconvert*.out
        retention-days: 2
