name: YouTube-Short-Daily

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    env:
      CLIENT_SECRETS_JSON: ${{ secrets.CLIENT_SECRETS_JSON }}
      TOKEN_JSON: ${{ secrets.TOKEN_JSON }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GAMEPLAY_URL: ${{ secrets.GAMEPLAY_URL }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Prepare params file
      run: echo '{}' > params.json

    - name: Execute notebook with Papermill
      uses: yaananth/run-notebook@v2
      env:
        RUNNER: ${{ toJson(runner) }}
        SECRETS: ${{ toJson(secrets) }}
        GITHUB: ${{ toJson(github) }}
      with:
        notebook: "Youtube Automation Trigger - Test 1.ipynb"
        params: "params.json"

    - name: Upload finished MP4
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: short
        path: shorts_final.mp4
